### ISSUE TITLE
`$savedip` indicator doesn't work as expected when on top frame

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#205]
Following PR #202 

```
$ gdb -ex start /bin/ls
```
![c2oyimz](https://user-images.githubusercontent.com/590234/35027433-916facae-fb05-11e7-9d5d-987cad66ee9f.png)

TODO: 
 - [x] revert the PR from `master` until fully tested (commit c758bb5)
 - [ ] live re-tests 
 - [ ] tests on non x86 arch

**Comment by etrickel-asu** [comment]
Bummer. I'm sorry it's not working right.

What OS is this ls from?  On Ubuntu 16.04, I am not seeing the same issue with /bin/ls or with a binary compiled with -03 (I thought maybe it was due to missing frame pointer).

What does the "info frame" output look like from gdb?  Also, would it be possible for you to post you gef.rc?

-Erik

**Comment by etrickel-asu** [comment]
Nevermind on the extra info, I was able to replicate it.  The "start" wasn't doing it for me, I had to break at the actual binary entry point.
The reason for the error, is along the lines of what you were concerned about, the "info frame" command did not supply a saved ip in this case
` rip = 0x4049a0; saved rip = <unavailable>`
I will add a check for this situation so that saved ip will not display.

**Comment by etrickel-asu** [comment]
I have a fix for it that checks for "saved.{1,7}=.?<unavailable>" and returns 0 in that case instead of finding a fandom address in the output.

Being kind of new to contributing to another's project, I'm not completely sure of the proper process here.  I pushed to dev in my fork, but I'm also adding a diff.  Should I do another PR?

[issue205_fix.txt](https://github.com/hugsy/gef/files/1639221/issue205_fix.txt)

**Comment by hugsy** [comment]
@etrickel-asu It's ok really :smile: I just don't work stuff not working fully to be in `master` because people might be complaining that it's not working hehe

I've moved it to the `dev` branch locally and will push it soon. This will give us plenty of time to test without risking complaints. I must say I didn't have time to test your PR before the merge, so now is good occasion. Also to improve it by making sure it supports all archs `gef` currently supports. So no big deal. And thanks for the patch...

**Comment by hugsy** [comment]
@etrickel-asu Your patch doesn't fix the issue I mentioned above. I've just retested with a fresh Debian Stretch on `/bin/ls` as well, same result (with https://raw.githubusercontent.com/etrickel-asu/gef/master/gef.py). The reason for that is precisely what I tried to explain earlier asking to rely as much as possible on GDB Python API instead of string parsing: 

![img](https://user-images.githubusercontent.com/590234/35081022-5933603a-fbc6-11e7-8722-b8b13a096037.png)

Whereas your patch looks only for the string `unavailable`.

String parsing / crazy RegExp what PEDA does everywhere and that's why PEDA will never exist on anything else than x86, so let's try not to take that path.

The cleanest approach is definitely using `gdb.Frame` along with the meta-register `$fp`, and define for each `Architecture` the method `get_saved_ip()` (since retrieving the saved IP is architecture-specific, this implementation makes sense). This way, you can simply replace in `DereferenceCommand.do_invoke()` 
```python
saved_ip = get_saved_ip()
```
with
```python
saved_ip = current_arch.get_saved_ip()
```

We can even  go further and define it as a property to get something super clean and Pythonic like 
```python
saved_ip = current_arch.saved_ip
```

And be 100% sure that it'll be portable and not depending on the output string from GDB.

**Comment by etrickel-asu** [comment]
Hi,

They just had to pick a different value for that field.  Again, bummer, 
but thanks for testing it out.  I should have done a positive search 
instead of a negative one and looked for a real address value after the 
equals sign.  Is the difference due to gdb version differences?

$fp will work on some platforms, but GDB does some magic to find the 
saved ip that I'm unfamiliar with even on x86.  For example, while 
looking into it this morning I found that when stack alignment is 2, 
saved ip is EBP+(ptr size), but when stack alignment is 16, it's not as 
straight forward the assembly seems to use ecx to save the non-aligned 
end of the prior frame.  I spent some time this morning trying to figure 
out how to do the calculation to derive the proper address, but couldn't 
come up with a way to determine the "stack alignment" from within gdb.

I understand your desire to make it as portable as possible and to rely 
on the most stable interfaces as possible.  I do not disagree.  I want 
gef to be as bug free and usable as possible too because I use it all 
the time!

In this case, the "info frame" call is a hack and as such it has 
limitations.  On the other hand, it also does a ton of work already.  It 
is offered in a somewhat similar format on all the platforms.  It also 
seems to handle the stack alignment problem.  It seems gdb saves the 
saved instruction pointer address (return address) in the prologue data 
for the frame and that's what gdb uses to return the value.

I can fix the issue you found. But should I?  Do you want to continue 
down this path or do you want me to take it the architecture by 
architecture route?

-Erik

**Comment by etrickel-asu** [comment]
Hi guys,
After spending some time looking for a solution to the things I discussed the other day, I gave up for now.  I cannot figure out how to tell from within gdb what the stack alignment is.  Although, I think I could probably add code that sets the alignment based on the disassembled prolog of any function kind of like the way gdb does it. 

However, I went ahead and created a more sophisticated patch for get_saved_ip().  The new version is much more specific and, as a result, is much more likely to end up not showing the label than accidentally labeling the wrong location.

I tested this version on ARM, AARCH64, MIPS, x86, and x86 64-bit.  I tested a simple binary and /bin/ls.  I couldn't replicate the <not saved> behavior, but this new version doesn't specifically rely on literal unavailable anymore. 

If you get a chance, please try out this one.

Thanks for your patience.
-Erik

**Comment by hugsy** [comment]
Hi Erik,

First of all, thanks for your effort. Finding accurately the correct saved ip is definitely no easy task. From what I've read, this patch is already a better first step into the universal solution I wanted. I'll test it this weekend if I can get a bit of spare time.

Thanks.

**Comment by hugsy** [comment]
And could you remind me why : 
```python
gdb.selected_frame().older().pc()
```
is not a clean viable to getting the saved IP for a given frame ?

I went our previous discussions (starting to get a lot), but I can't find the answer.

**Comment by hugsy** [comment]
Ok, so I've spend some time on it, and I've actually managed to achieve this (useful) feature in a pure Pythonic way: 

My approach consists in looking at the dereferenced address in `pprint_dereferenced()`, and if one of the values is equal to `gdb.selected_frame().older().pc()` (I added some checks for taking into consideration the first frame), then I add the information that it is the `saved_ip`.

This approach has a few advantages: pure Python (no string parsing), less code, faster execution (I only re-use information already fetched), and last but not least, works universally (tested x86 & arm so far, I'll do the rest later):

![img](https://user-images.githubusercontent.com/590234/35190052-7720ad98-fe0d-11e7-8619-73fe668aa8f9.png)

I think it's a useful information, so it will always be displayed (no need for the `context.show_saved_ip` setting anymore).

See the commit above for diff. Feel free to test. 

Thanks!

**Comment by etrickel-asu** [comment]
Good morning,

I remember discussing selected_frame.fp but I don't recall discussing older().pc. 
It is an interesting idea, but I have two issues we will need to work through. First, there's a potential for duplicate labels.  Since the code is doing a search instead using the precise savedip location, if that location appears in the displayed stack more than once the label will be applied.  One idea to prevent this is to label the address closest to $fp, but on some architectures I think the stacked saved ip will be the one that's closer to the $sp. 
![x86-64-repated-current-frame-savedip](https://user-images.githubusercontent.com/14295821/35194739-728c068e-fe75-11e7-8f71-4bf59a656d01.png)
Second, using older() means that we will not have the current_frame_savedip label available when only one frame is in the stack even though it does exist via the `info frame`.  In the real world executables this isn't really an issue, but it often comes up when looking at ctf binaries.
![top-frame-no-saved-ip](https://user-images.githubusercontent.com/14295821/35194748-8616bef6-fe75-11e7-8805-77ea95454e34.png)

Also, I was disappointed the functionality that always displays the saved ip was removed.  When using gef, I have found always having the savedip label useful.  First, knowing where the savedip is located makes it faster to create the right sized payload.  Second, it's helpful to have a rough idea of the stack size.  Maybe we could replace the show_saved_ip config with "always show saved ip" option?  This is the real reason why I had made it optional because it adds 2 or 3 lines to the stack output.  
![show-bottom-stack](https://user-images.githubusercontent.com/14295821/35194879-fb0810c8-fe77-11e7-9057-24750b565322.png)

Thanks for all the help,
Erik

**Comment by hugsy** [comment]
I should have mentioned that before, the "show full stack" feature is being put in an external command (not part of `context`) - for the moment called `current-stack-frame` (name might change, if you have a better, I'm all ears :smile: ). The reason for that is that I don't think the context view should have clobbered data. Additionally using an external command makes it cleaner and allows to filter with more granularity the conditions where this command will work since it is not really cross-architecture.

Right now, the command `current-stack-frame`  run without argument will spit out the same clobbered display than in your screenshot, but if provided with `full` argument, it will display the entire stack for the current function context, which is useful (especially for beginner learning stack overflow and such). I will push it soon to [gef-scripts](https://github.com/hugsy/gef-scripts) when I have tested it enough.

For the duplicate issue with $savedip I am aware of that, what I send is a first gist (that's why it is in the `dev` branch) which will be perfected over time. This feature is a WIP since it is not as easy as expected to implement especially in cross-architecture way. PR-ing into `master` the first time was a mistake, so I want to make sure that the second time we do, it works all the time, everywhere.

Cheers.

**Comment by etrickel-asu** [comment]
Thanks for the response.

I am looking forward to the final version :)

-Erik

**Comment by hugsy** [comment]
It starts to look good: after realizing that there were a lot of similar code, I moved it all in the external command [`current-stack-frame`](https://github.com/hugsy/gef-scripts/blob/master/stack.py), and the result happens to be quite nice, for example on AARCH64:

![img](https://user-images.githubusercontent.com/590234/35203748-a4c46402-fede-11e7-8c97-035056dedca3.png)

I believe this is much cleaner, especially when dealing with functions with huge stacks (`context` will still be readable, and `current-stack-frame` will detail everything there is to know about the stack).

**Comment by etrickel-asu** [comment]
I like it.  Thanks!

**Comment by hugsy** [comment]
Honestly me too :smile: This new command is sure gonna be helpful ! Kudos @etrickel-asu

**Comment by hugsy** [comment]
So I've been using this command like this and it seems that the setup works pretty well. I'll close the ticket and leave this new command as part of `gef-scripts` for now. 
It'll be integrated into `gef` when it's been real-life proofed enough :)

Kudos to @etrickel-asu , this command was a good idea.
